# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore Dependencies
        run: dotnet restore    

      - name: Build Project
        run: dotnet build -c Release --no-restore

      - name: Run Unit Tests
        run: dotnet test -c Release --no-build

      - name: Publish Project
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/myapp"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production' 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app     

